name: goe-wallet-ci

on:
  push:
    branches:
      - 'test'
  workflow_dispatch:

jobs:
  wallet-create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install

      - run: yarn build

      - name: Run Wallet Create CI Test
        run: node test/createWalletCI.mjs
